package com.company.AccountOOP;

public class Account {

//    Using OOP, create a Class Account, which has fields Login*, Password*,
//    Firstname*, Lastname*, Age*, City, Place of work, Family status, ID.
//Fields marked with star * are mandatory
//Create several constructors (for all mandatory and each non-mandatory fields)
//ID has to be generated by program and assigned to each new account
//Implement Encapsulation with restrictions (like age cannot be negative number and etc)
//In new Class, create three users
//For user1 - change firstname
//For user2 - change City
//For user3 - change both login and password
//Printout fields before and after the change of each user

        private String login;
        private String password;
        private String firstName;
        private String lastName;
        private int age;
        private String city;
        private String placeOfWork;
        private String familyStatus;
        private int id;
        private static int counter = 10000;


        public Account(String login, String password, String firstName, String lastName, int age) {
            this.login = login;
            this.password = password;
            this.firstName = firstName;
            this.lastName = lastName;
            this.age = age;
            this.id = counter++;
        }

        public Account(String login, String password, String firstName, String lastName, int age, String city) {
            this.login = login;
            this.password = password;
            this.firstName = firstName;
            this.lastName = lastName;
            this.age = age;
            this.city = city;
            this.id = counter++;
        }

        public Account(String login, String password, String firstName, String lastName, int age, String city, String placeOfWork) {
            this.login = login;
            this.password = password;
            this.firstName = firstName;
            this.lastName = lastName;
            this.age = age;
            this.city = city;
            this.placeOfWork = placeOfWork;
            this.id = counter++;
        }

        public Account(String login, String password, String firstName, String lastName, int age, String city, String placeOfWork, String familyStatus) {
            this.login = login;
            this.password = password;
            this.firstName = firstName;
            this.lastName = lastName;
            this.age = age;
            this.city = city;
            this.placeOfWork = placeOfWork;
            this.familyStatus = familyStatus;
            this.id = counter++;
        }

        public String getLogin() {
            return login;
        }

        public void setLogin(String login) {
            if (login.length() >= 5) {
                this.login = login;
            } else {
                System.err.println("Login can't be less than 5 characters");
            }
        }

        public String getPassword() {
            return password;
        }

        public void setPassword(String password) {
            if (password.length() >= 8) {
                this.password = password;
            } else {
                System.err.println("Password can't be less than 8 characters");
            }
        }

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }

        public int getAge() {
            return age;
        }

        public void setAge(int age) {
            if (age >= 0) {
                this.age = age;
            } else {
                System.err.println("Age can't be negative number");
            }
        }

        public String getCity() {
            return city;
        }

        public void setCity(String city) {
            this.city = city;
        }

        public String getPlaceOfWork() {
            return placeOfWork;
        }

        public void setPlaceOfWork(String placeOfWork) {
            this.placeOfWork = placeOfWork;
        }

        public String getFamilyStatus() {
            return familyStatus;
        }

        public void setFamilyStatus(String familyStatus) {
            this.familyStatus = familyStatus;
        }

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }

    }

